Route21_South_MapScripts::
	.byte 0


CinnabarWoodSign::
# 6 "data/maps/Route21_South/scripts.pory"
	lockall
# 7 "data/maps/Route21_South/scripts.pory"
	msgbox CinnabarWoodSign_Text_0
# 8 "data/maps/Route21_South/scripts.pory"
	closemessage
# 9 "data/maps/Route21_South/scripts.pory"
	releaseall
	end


CinnabarWoodSign_Text_0:
# 7 "data/maps/Route21_South/scripts.pory"
	.string "Cinnabar Woods. A tiny island forest.$"
