# 1 "data/maps/Route18_EastEntrance_2F/scripts.pory"

# 2 "data/maps/Route18_EastEntrance_2F/scripts.pory"
Route18_EastEntrance_2F_MapScripts::
# 3 "data/maps/Route18_EastEntrance_2F/scripts.pory"
	.byte 0
# 4 "data/maps/Route18_EastEntrance_2F/scripts.pory"

# 5 "data/maps/Route18_EastEntrance_2F/scripts.pory"
Route18_EastEntrance_2F_EventScript_LeftBinoculars::
# 6 "data/maps/Route18_EastEntrance_2F/scripts.pory"
	msgbox Route18_EastEntrance_2F_Text_PalletTownInWest, MSGBOX_SIGN
# 7 "data/maps/Route18_EastEntrance_2F/scripts.pory"
	end
# 8 "data/maps/Route18_EastEntrance_2F/scripts.pory"

# 9 "data/maps/Route18_EastEntrance_2F/scripts.pory"
Route18_EastEntrance_2F_EventScript_RightBinoculars::
# 10 "data/maps/Route18_EastEntrance_2F/scripts.pory"
	msgbox Route18_EastEntrance_2F_Text_PeopleSwimming, MSGBOX_SIGN
# 11 "data/maps/Route18_EastEntrance_2F/scripts.pory"
	end

Aanahpretty1::
# 16 "data/maps/Route18_EastEntrance_2F/scripts.pory"
	lockall
# 17 "data/maps/Route18_EastEntrance_2F/scripts.pory"
	msgbox Aanahpretty1_Text_0
# 18 "data/maps/Route18_EastEntrance_2F/scripts.pory"
	closemessage
# 19 "data/maps/Route18_EastEntrance_2F/scripts.pory"
	msgbox Aanahpretty1_Text_1
# 20 "data/maps/Route18_EastEntrance_2F/scripts.pory"
	closemessage
# 21 "data/maps/Route18_EastEntrance_2F/scripts.pory"
	releaseall
	end


Aanahpretty1_Text_0:
# 17 "data/maps/Route18_EastEntrance_2F/scripts.pory"
	.string "Aanah is so pretty <3333 I think I\n"
	.string "am in love.$"

Aanahpretty1_Text_1:
# 19 "data/maps/Route18_EastEntrance_2F/scripts.pory"
	.string "I think I'm going to message her on\n"
	.string "instagram and offer her money for\l"
	.string "picutures of the bottom of her feet\l"
	.string "<333$"
