Route102House_MapScripts::
	.byte 0


R102fisher1::
# 6 "data/maps/Route102House/scripts.pory"
	lockall
# 7 "data/maps/Route102House/scripts.pory"
	msgbox R102fisher1_Text_0
# 8 "data/maps/Route102House/scripts.pory"
	closemessage
# 9 "data/maps/Route102House/scripts.pory"
	releaseall
	end


R102fisher1_Text_0:
# 7 "data/maps/Route102House/scripts.pory"
	.string "What are you doing in here? This is\n"
	.string "my private fishing house! Get the\l"
	.string "fuck out before you get shot!$"
