VermilionCity_House2_MapScripts::
	.byte 0


VCHgirl1::
# 6 "data/maps/VermilionCity_House2/scripts.pory"
	msgbox VCHgirl1_Text_0
# 7 "data/maps/VermilionCity_House2/scripts.pory"
	closemessage
# 8 "data/maps/VermilionCity_House2/scripts.pory"
	msgbox VCHgirl1_Text_1
	return


VCHgirl1_Text_0:
# 6 "data/maps/VermilionCity_House2/scripts.pory"
	.string "Back in 1999, when Red and Blue\n"
	.string "version were new. There was a\l"
	.string "rumor, that you could find a Mew\l"
	.string "under the truck!$"

VCHgirl1_Text_1:
# 8 "data/maps/VermilionCity_House2/scripts.pory"
	.string "You should google it!$"
